version: '3.3'
services:

  flask:
    extends:
      file: docker-compose.yml
      service: flask
    environment:
      FLASK_DEBUG: 0

  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod

    depends_on:
      - flask
    environment:
      - NGINX_CONF_FILE=nginx.prod.conf
    volumes:
      - /etc/letsencrypt/live/www.kaizens.guide/cert.pem:/ssl/cert.pem
      - /etc/letsencrypt/live/www.kaizens.guide/privkey.pem:/ssl/privkey.pem