version: '3.3'
services:
    flask:
        build: ./flaskapp
        container_name: flask
        restart: always
        environment:
          APP_NAME: FlaskBookApp
          FLASK_DEBUG: 1
          FLASK_ENV: "production"
        expose:
          - 8080
        volumes:
          - ./flaskapp/src:/app/src


    nginx:
        build:
          context: ./nginx
          dockerfile: Dockerfile
        container_name: nginx
        restart: always
        ports:
          - "80:80"
          - "443:443"
        depends_on:
          - flask


