version: '3.3'
services:
    flask:
        build: ./flaskapp
        container_name: flask
        restart: always
        environment:
          - APP_NAME=MyFlaskApp
          - DEV=DEVELOPMENT
        expose:
          - 8080
        volumes:
          - ./flaskapp/src:/app/src


    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        environment:
          - "DEV=DEVELOPMENT"
          - "NGINX_CONF_FILE=nginx.conf"
        ports:
          - "80:80"
          - "443:443"
        depends_on:
          - flask


