version: '2.4'
services:

  webpack:
      build: ./webpack
      container_name: webpack
      environment:
        DIGEST_FOLDER_NAME: _dist
      volumes:
        - ./webpack/pack_assets.sh:/pack_assets.sh:Z
        - ./flaskapp/:/flask_data
        - ./webpack/digest_html.py:/digest_html.py:Z
      command: /bin/bash -c "./pack_assets.sh"

  flask:
      build: ./flaskapp
      container_name: flask
      restart: always
      environment:
        APP_NAME: FlaskBookApp
        FLASK_DEBUG: 1
        FLASK_ENV: "development"
        DIGEST_FOLDER_NAME: _dist
      expose:
        - 8080
      volumes:
        - ./flaskapp/:/flask_data
      command: ["uwsgi", "/flask_data/app.ini"]

  nginx:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      container_name: nginx
      restart: always
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - flask







