version: '3.8'
services:




  flask:
    extends:
      file: docker-compose.yml
      service: flask
    environment:
      FLASK_DEBUG: 0
      FLASK_ENV: "production"

  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod

    depends_on:
      - flask
    environment:
      - NGINX_CONF_FILE=nginx.prod.conf
    volumes:
      - /root/cert.pem:/ssl/cert.pem
      - /root/key.pem:/ssl/key.pem

