version: '3.3'
services:
    flask:
        build: ./flaskapp
        container_name: flask
        restart: always
        environment:
          - APP_NAME=MyFlaskApp
        expose:
          - 8080
        volumes:
          - ./flaskapp/src:/app/src


    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
          - "80:80"
          - "443:443"
        depends_on:
          - flask
        volumes:
          - /etc/letsencrypt/live/www.kaizens.guide/cert.pem:/ssl/cert.pem
          - /etc/letsencrypt/live/www.kaizens.guide/privkey.pem:/ssl/privkey.pem
